apiVersion: v1
kind: Service
metadata:
  name: azure-service-minecraft
  labels:
    app: 'minecraft-label'
spec:
  type: LoadBalancer
  ports:
  - name: myport
    port: 25565
    targetPort: 25565
  selector:
    app: minecraft