apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: azure-statefulset-minecraft
spec:
  selector:
    matchLabels:
      app: minecraft # has to match .spec.template.metadata.labels
  serviceName: azure-service-minecraft
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: minecraft # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: minecraft
        image: openhack/minecraft-server:2.0
        env:
        - name: EULA
          value: "TRUE"
        ports:
        - containerPort: 25565
        volumeMounts:
        - name: www
          mountPath: /data  
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "managed-premium"
      resources:
        requests:
          storage: 1Gi